# Generated by Django 5.1.1 on 2024-10-25 06:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdm', '0002_student_created_at_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_number',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdm.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdm.teacher')),
            ],
        ),
    ]
