# Generated by Django 5.1.1 on 2024-10-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdm', '0002_student_user_alter_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
