# Generated by Django 5.0.4 on 2024-10-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdm', '0003_rename_teacher_number_teacher_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_course',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
