# Generated by Django 5.1.1 on 2024-10-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdm', '0003_student_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
