# Generated by Django 5.0.4 on 2024-10-27 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdm', '0004_student_enrolled_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_course',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='sdm.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, to='sdm.course'),
        ),
    ]
