# Generated by Django 5.1.1 on 2024-11-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdm', '0005_remove_student_enrolled_course_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.CharField(max_length=100)),
                ('admin_pass', models.CharField(max_length=100)),
                ('admin_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
