# Generated by Django 5.1.1 on 2024-11-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdm', '0006_admin_alter_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admin_email',
        ),
    ]
