# Generated by Django 5.1.1 on 2024-11-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdm', '0007_remove_admin_admin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_email',
            field=models.CharField(default='wow@gmail.com', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
