# Generated by Django 5.0.4 on 2024-11-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdm', '0008_remove_admin_id_admin_admin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('teachers', models.ManyToManyField(related_name='subjects', to='sdm.teacher')),
            ],
        ),
    ]
