# Generated by Django 5.0.4 on 2024-11-17 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdm', '0009_remove_teacher_subject_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(default='Blank', on_delete=django.db.models.deletion.CASCADE, to='sdm.course'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
